"""Constants used across the application"""

PLUGIN_JSONRPC_TYPE_REQUEST = "WOX_JSONRPC_REQUEST"
PLUGIN_JSONRPC_TYPE_RESPONSE = "WOX_JSONRPC_RESPONSE"
PLUGIN_JSONRPC_TYPE_SYSTEM_LOG = "WOX_JSONRPC_SYSTEM_LOG"
