package app

import (
	"context"
	"errors"
	"strings"
	"testing"
	"wox/common"
	"wox/util"
)

type preparingExtraAppsRetriever struct {
	Retriever
	called bool
}

func (r *preparingExtraAppsRetriever) PrepareExtraApps(_ context.Context, apps []appInfo) []appInfo {
	r.called = true
	return apps
}

func TestShouldIndexAppsFolderAppID(t *testing.T) {
	testCases := []struct {
		appID string
		want  bool
	}{
		{appID: `Microsoft.WindowsCalculator_8wekyb3d8bbwe!App`, want: true},
		{appID: `music.youtube.com-5929F88E_vezhnr0wkvrcy!App`, want: true},
		{appID: `Microsoft.MicrosoftEdge.Stable_8wekyb3d8bbwe!https://music.youtube.com/`, want: true},
		{appID: `https://pixpin.cn`, want: true},
		{appID: `http://localhost/app`, want: true},
		{appID: `MSEdgePWA-abc123`, want: true},
		{appID: `Chrome._crx_nngceckbapebfimnlniiiahkandclblb`, want: true},
		{appID: `{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\magnify.exe`, want: true},
		{appID: `{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\cmd.exe`, want: true},
		{appID: `{F38BF404-1D43-42F2-9305-67DE0B28FC23}\regedit.exe`, want: true},
		{appID: `{D65231B0-B2F1-4857-A4CE-A8E7C6EA7D27}\odbcad32.exe`, want: true},
		{appID: `Microsoft.Windows.Explorer`, want: true},
		{appID: `Microsoft.Windows.ControlPanel`, want: true},
		{appID: `Microsoft.Windows.Shell.RunDialog`, want: true},
		{appID: `Chrome`, want: false},
		{appID: `MSEdge`, want: false},
		{appID: `C:\Users\qianl\scoop\apps\vscode\current\Code.exe`, want: false},
		{appID: `{6D809377-6AF0-444B-8957-A3773F02200E}\Notepad++\notepad++.exe`, want: false},
		{appID: `Microsoft.AutoGenerated.{3741D7D3-67BD-AD73-D5CC-1A783842E6D9}`, want: false},
		{appID: ``, want: false},
		{appID: `   `, want: false},
	}

	for _, testCase := range testCases {
		if got := shouldIndexAppsFolderAppID(testCase.appID); got != testCase.want {
			t.Fatalf("shouldIndexAppsFolderAppID(%q) = %t, want %t", testCase.appID, got, testCase.want)
		}
	}
}

func TestAppsFolderEntryType(t *testing.T) {
	if got := appsFolderEntryType(appsFolderEntry{Packaged: true}); got != AppTypeUWP {
		t.Fatalf("packaged entry type = %q", got)
	}
	if got := appsFolderEntryType(appsFolderEntry{}); got != AppTypeAppsFolder {
		t.Fatalf("virtual entry type = %q", got)
	}
}

func TestExtraAppsFromFolderEntriesReusesCachedIconsAndAddsNewPWAs(t *testing.T) {
	existingPath := extraAppPath(`Microsoft.WindowsCalculator_8wekyb3d8bbwe!App`)
	existing := appInfo{
		Name: "Calculator",
		Path: existingPath,
		Icon: common.WoxImage{ImageType: common.WoxImageTypeAbsolutePath, ImageData: `C:\cache\calc.png`},
		Type: AppTypeUWP,
	}
	entries := []appsFolderEntry{
		{Name: "计算器", AppID: `Microsoft.WindowsCalculator_8wekyb3d8bbwe!App`, Packaged: true},
		{Name: "YouTube Music", AppID: `music.youtube.com-5929F88E_vezhnr0wkvrcy!App`},
		{Name: "Chrome", AppID: "Chrome"},
	}

	got := extraAppsFromFolderEntries(entries, map[string]appInfo{strings.ToLower(existingPath): existing}, strings.ToLower)
	if len(got) != 2 {
		t.Fatalf("got %d extras, want 2", len(got))
	}
	if got[0].Name != "计算器" || got[0].Icon.ImageData != existing.Icon.ImageData {
		t.Fatalf("expected reused calculator with updated name, got %#v", got[0])
	}
	if got[1].Name != "YouTube Music" || got[1].Type != AppTypeAppsFolder {
		t.Fatalf("expected new PWA entry, got %#v", got[1])
	}
	if got[1].Icon.ImageData != appIcon.ImageData {
		t.Fatalf("discovery should leave new app icons for indexing, got %#v", got[1].Icon)
	}
	if !got[1].IsDefaultIcon {
		t.Fatal("new AppsFolder candidate must be marked as using the default icon")
	}
}

type failingExtraAppsRetriever struct {
	Retriever
}

func (r *failingExtraAppsRetriever) ListExtraApps(context.Context, map[string]appInfo) ([]appInfo, error) {
	return []appInfo{{Name: "Partial", Path: extraAppPath("partial!App")}}, errors.New("incomplete enumeration")
}

func (r *failingExtraAppsRetriever) GetPlatform() string {
	return util.PlatformWindows
}

// TestReconcileExtraAppsPreservesIndexOnEnumerationFailure covers partial snapshots.
func TestReconcileExtraAppsPreservesIndexOnEnumerationFailure(t *testing.T) {
	existing := appInfo{Name: "Installed", Path: extraAppPath("installed!App"), Type: AppTypeUWP}
	app := &ApplicationPlugin{api: newRecordingAppAPI(), retriever: &failingExtraAppsRetriever{}, apps: []appInfo{existing}}
	if app.reconcileExtraApps(context.Background()) || len(app.apps) != 1 || !app.apps[0].equals(existing) {
		t.Fatal("failed enumeration changed the existing index")
	}
}

// TestIndexExtraAppsClassifiesFinalIcons covers both fallback and resolved icons.
func TestIndexExtraAppsClassifiesFinalIcons(t *testing.T) {
	app := &ApplicationPlugin{api: newRecordingAppAPI(), retriever: &preparingExtraAppsRetriever{}}
	apps := app.indexExtraApps(context.Background(), []appInfo{
		{Name: "Fallback", Path: extraAppPath("fallback!App"), Icon: appIcon},
		{Name: "Resolved", Path: extraAppPath("resolved!App"), Icon: common.NewWoxImageAbsolutePath(`C:\cache\resolved.png`), IsDefaultIcon: true},
	}, nil)
	if !apps[0].IsDefaultIcon || app.shouldShowInLaunchpad(apps[0]) {
		t.Fatal("default icon should be excluded from Launchpad")
	}
	if apps[1].IsDefaultIcon || !app.shouldShowInLaunchpad(apps[1]) {
		t.Fatal("resolved icon should be eligible for Launchpad")
	}
}

func TestMergeExtraAppsAddsAndRemovesAppsFolderEntries(t *testing.T) {
	desktop := appInfo{Name: "Cursor", Path: `C:\Apps\Cursor.exe`, Type: AppTypeDesktop}
	oldExtra := appInfo{Name: "Old PWA", Path: extraAppPath("old.example!App"), Type: AppTypeAppsFolder}
	newExtra := appInfo{Name: "YouTube Music", Path: extraAppPath(`music.youtube.com-5929F88E_vezhnr0wkvrcy!App`), Type: AppTypeAppsFolder}

	kept, added, removed, changed := mergeExtraApps(
		[]appInfo{desktop, oldExtra},
		[]appInfo{newExtra},
		strings.ToLower,
	)
	if !changed {
		t.Fatal("expected extra app set to change")
	}
	if len(kept) != 1 || kept[0].Path != desktop.Path {
		t.Fatalf("desktop app should stay, got %#v", kept)
	}
	if len(added) != 1 || added[0].Path != newExtra.Path {
		t.Fatalf("expected YouTube Music to be added, got %#v", added)
	}
	if len(removed) != 1 || removed[0] != oldExtra.Name {
		t.Fatalf("expected old PWA to be removed, got %#v", removed)
	}
}

func TestIndexExtraAppsUsesPlatformPreparation(t *testing.T) {
	retriever := &preparingExtraAppsRetriever{}
	app := &ApplicationPlugin{api: newRecordingAppAPI(), retriever: retriever}

	app.indexExtraApps(context.Background(), []appInfo{{Name: "YouTube", Path: extraAppPath("youtube!App"), Type: AppTypeUWP}}, nil)

	if !retriever.called {
		t.Fatal("extra app indexing skipped platform metadata and icon preparation")
	}
}
