version: 1.2.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-beta.2-$(APPVEYOR_REPO_COMMIT)'
before_build:
- ps: nuget restore
build:
  project: Wox.sln
after_test:
- ps: >-
    .\Deploy\UpdateGenerator\build.ps1

    .\Deploy\Nuget\pack.ps1
artifacts:
- path: Output\Release
  name: release-binary
- path: '*.nupkg'
  name: nugetpackage
- path: Output\Update
  name: update-binary
deploy:
- provider: NuGet
  api_key:
    secure: yybUOFgBuGVpbmOVZxsurC8OpkClzt9dR+/54WpMWcq6b6oyMatciaelRPnXsjRn
  artifact: nugetpackage
  on:
    branch: api
