version: 1.2.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
- ps: nuget restore
build:
  project: Wox.sln
after_test:
- ps: >-
    .\Deploy\nuget.ps1
    
    .\Deploy\build-release.ps1
artifacts:
- path: 'Wox-*.zip'
  name: release_binary
- path: '*.nupkg'
  name: nuget_package
deploy:
- provider: NuGet
  api_key:
    secure: yybUOFgBuGVpbmOVZxsurC8OpkClzt9dR+/54WpMWcq6b6oyMatciaelRPnXsjRn
  artifact: nuget_package
  on:
    branch: api
