package plugin

import (
	"wox/common"
)

type WoxPreviewType = string
type WoxPreviewScrollPosition = string

const (
	WoxPreviewTypeMarkdown = "markdown"
	WoxPreviewTypeText     = "text"
	WoxPreviewTypeImage    = "image" // when type is image, data should be WoxImage.String()
	WoxPreviewTypeUrl      = "url"
	WoxPreviewTypeFile     = "file"   // when type is file(can be *.md, *.jpg, *.pdf and so on), data should be url/filepath
	WoxPreviewTypeRemote   = "remote" // when type is remote, data should be url to load WoxPreview
	WoxPreviewTypeTerminal = "terminal"
	WoxPreviewTypeWebView  = "webview" // when type is webview, data should be JSON string of WoxPreviewWebviewData
	// list is the generic structured preview used for status-oriented rows.
	// It replaces the old file-only preview so plugins can reuse the same
	// surface for progress lists, selected files, and other non-file workflows.
	WoxPreviewTypeList = "list"

	// internal use
	WoxPreviewTypePluginDetail = "plugin_detail" // when type is plugin_detail, data should be JSON string of plugin metadata
	WoxPreviewTypeChat         = "chat"          // when type is chat, data should be JSON string of common.AIChatPreviewData. this type is only for ai chat plugin
	WoxPreviewTypeUpdate       = "update"        // internal update UI, data should be JSON string
	WoxPreviewTypeAIStream     = "ai_stream"
	// query_requirement_settings is generated by core when plugin metadata declares
	// missing query prerequisites. The UI renders it as a focused settings form
	// instead of letting grid/list result density hide the actionable problem.
	WoxPreviewTypeQueryRequirementSettings = "query_requirement_settings"
	// theme_edit is generated by core for the built-in theme editor. The UI renders
	// it as the same full-preview editor used by settings.
	WoxPreviewTypeThemeEdit = "theme_edit"
	// trigger_keyword_conflict is generated by core when multiple enabled plugins
	// own the same concrete trigger keyword. The UI renders an editable conflict
	// resolver because normal plugin dispatch is intentionally blocked.
	WoxPreviewTypeTriggerKeywordConflict = "trigger_keyword_conflict"
	// hotkey_overview is generated by core for the built-in shortcut reference.
	// Flutter renders it from current settings so core does not duplicate UI-only hotkeys.
	WoxPreviewTypeHotkeyOverview = "hotkey_overview"
)

const (
	WoxPreviewScrollPositionBottom = "bottom" // scroll to bottom after preview first show
)

// WoxPreviewTag is the metadata chip contract shown below the preview content.
// PreviewProperties used to force metadata into a key/value shape even though
// the UI now displays compact tags, so tags keep the visible label separate
// from the optional explanatory tooltip.
type WoxPreviewTag struct {
	Label   string
	Tooltip string
}

type WoxPreview struct {
	PreviewType WoxPreviewType
	PreviewData string
	// PreviewOverlayData is the optional full-size image payload used when the UI opens an image
	// preview in the native overlay. PreviewData often points at a lightweight thumbnail, which is
	// correct for the inline preview but not enough for the click-to-enlarge flow.
	PreviewOverlayData string
	PreviewTags        []WoxPreviewTag
	// Deprecated: use PreviewTags instead. The UI still maps each legacy key/value
	// pair to a tag with value as Label and key as Tooltip so older plugins keep
	// their compact metadata display without changing their payload.
	PreviewProperties map[string]string // key support i18n
	ScrollPosition    WoxPreviewScrollPosition
}

func (p *WoxPreview) IsEmpty() bool {
	return p.PreviewData == ""
}

// WoxPreviewListData is the shared JSON contract for list previews.
// The payload is row-based instead of file-path-based so plugins can update the
// same preview during long-running work without inventing custom markdown.
type WoxPreviewListData struct {
	Items []WoxPreviewListItem `json:"items"`
}

// WoxPreviewListItem mirrors the launcher result row surface inside preview.
// Tails intentionally reuse QueryResultTail so status chips and semantic
// colors stay consistent between result rows and preview rows.
type WoxPreviewListItem struct {
	Icon     *common.WoxImage  `json:"icon,omitempty"`
	Title    string            `json:"title"`
	Subtitle string            `json:"subtitle,omitempty"`
	Tails    []QueryResultTail `json:"tails,omitempty"`
}

type WoxPreviewChatData struct {
	Conversations []common.Conversation
	Model         common.Model
}

type WoxPreviewWebviewData struct {
	Url           string `json:"url"`
	InjectCss     string `json:"injectCss,omitempty"`
	UserAgent     string `json:"userAgent,omitempty"`
	CacheDisabled bool   `json:"cacheDisabled,omitempty"`
}
