package plugin

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"wox/common"
	"wox/i18n"
	"wox/setting/definition"
	"wox/setting/validator"
	"wox/util"

	"github.com/samber/lo"
)

type queryRequirementFailure struct {
	Requirement       MetadataQueryRequirement
	SettingDefinition definition.PluginSettingDefinitionItem
	Value             string
	Message           string
}

type queryRequirementSettingsPreviewRequirement struct {
	SettingKey string
	Message    string
}

type queryRequirementSettingsPreviewData struct {
	PluginId           string
	PluginName         string
	Title              string
	Message            string
	Requirements       []queryRequirementSettingsPreviewRequirement
	SettingDefinitions definition.PluginSettingDefinitions
	Values             map[string]string
}

func (m *Manager) buildQueryRequirementSettingsResult(ctx context.Context, pluginInstance *Instance, query Query) (QueryResult, bool) {
	failures := m.validateQueryRequirements(ctx, pluginInstance, query)
	if len(failures) == 0 {
		return QueryResult{}, false
	}

	pluginName := pluginInstance.GetName(ctx)
	title := fmt.Sprintf(i18n.GetI18nManager().TranslateWox(ctx, "plugin_query_requirement_settings_title"), pluginName)
	message := failures[0].Message
	if message == "" {
		message = i18n.GetI18nManager().TranslateWox(ctx, "plugin_query_requirement_settings_message")
	}

	values := map[string]string{}
	requirements := make([]queryRequirementSettingsPreviewRequirement, 0, len(failures))
	settingDefinitions := make(definition.PluginSettingDefinitions, 0, len(failures))
	for _, failure := range failures {
		key := failure.Requirement.SettingKey
		values[key] = failure.Value
		requirements = append(requirements, queryRequirementSettingsPreviewRequirement{
			SettingKey: key,
			Message:    failure.Message,
		})

		// The preview must validate the same rules that blocked the query. When
		// the requirement declares its own validators, copy them onto the setting
		// definition before sending the compact form to the UI.
		settingDefinition := m.withEffectiveRequirementValidators(failure.SettingDefinition, m.getEffectiveQueryRequirementValidators(failure.Requirement, failure.SettingDefinition))
		if settingDefinition.Value != nil {
			settingDefinition.Value = settingDefinition.Value.Translate(pluginInstance.API.GetTranslation)
		}
		settingDefinitions = append(settingDefinitions, settingDefinition)
	}

	previewData, marshalErr := json.Marshal(queryRequirementSettingsPreviewData{
		PluginId:           pluginInstance.Metadata.Id,
		PluginName:         pluginName,
		Title:              title,
		Message:            message,
		Requirements:       requirements,
		SettingDefinitions: settingDefinitions,
		Values:             values,
	})
	if marshalErr != nil {
		logger.Error(ctx, fmt.Sprintf("<%s> failed to marshal query requirement settings preview: %s", pluginName, marshalErr.Error()))
		return QueryResult{}, false
	}

	overlayIcon := common.NewWoxImageEmoji("⚠️")
	pluginIcon := common.ParseWoxImageOrDefault(pluginInstance.Metadata.Icon, overlayIcon)
	icon := pluginIcon.OverlayFullPercentage(overlayIcon, 0.45)

	// The requirement result is generated by core instead of the plugin. Returning
	// it directly prevents the plugin query from running with missing credentials
	// and gives the UI a full preview form instead of a cramped grid item.
	return QueryResult{
		Title:    title,
		SubTitle: message,
		Icon:     icon,
		Preview: WoxPreview{
			PreviewType: WoxPreviewTypeQueryRequirementSettings,
			PreviewData: string(previewData),
		},
		Actions: []QueryResultAction{
			m.newOpenPluginSettingAction(ctx, pluginInstance),
		},
		Score: 1000000,
	}, true
}

func (m *Manager) validateQueryRequirements(ctx context.Context, pluginInstance *Instance, query Query) []queryRequirementFailure {
	requirements := pluginInstance.Metadata.QueryRequirements.GetRequirementsForQuery(query)
	if len(requirements) == 0 {
		return nil
	}

	failures := []queryRequirementFailure{}
	for _, requirement := range requirements {
		settingDefinition, found := m.resolveQueryRequirementSettingDefinition(ctx, pluginInstance, requirement.SettingKey)
		if !found {
			logger.Error(ctx, fmt.Sprintf("<%s> query requirement setting not found: %s", pluginInstance.GetName(ctx), requirement.SettingKey))
			continue
		}

		validators := m.getEffectiveQueryRequirementValidators(requirement, settingDefinition)
		if len(validators) == 0 {
			// Metadata authors can deliberately use setting validators as the source
			// of truth, but an empty combined validator set cannot decide readiness.
			logger.Error(ctx, fmt.Sprintf("<%s> query requirement has no validators: %s", pluginInstance.GetName(ctx), requirement.SettingKey))
			continue
		}

		value := pluginInstance.API.GetSetting(ctx, requirement.SettingKey)
		if validationMessage := validateQueryRequirementValue(value, validators); validationMessage != "" {
			message := m.translateQueryRequirementMessage(ctx, pluginInstance, requirement.Message, validationMessage)
			failures = append(failures, queryRequirementFailure{
				Requirement:       requirement,
				SettingDefinition: settingDefinition,
				Value:             value,
				Message:           message,
			})
		}
	}

	return failures
}

func (m *Manager) resolveQueryRequirementSettingDefinition(ctx context.Context, pluginInstance *Instance, key string) (definition.PluginSettingDefinitionItem, bool) {
	for _, item := range pluginInstance.Metadata.SettingDefinitions {
		if item.Value == nil || item.Value.GetKey() != key {
			continue
		}
		if lo.Contains(item.DisabledInPlatforms, util.GetCurrentPlatform()) {
			return definition.PluginSettingDefinitionItem{}, false
		}
		if item.Type != definition.PluginSettingDefinitionTypeDynamic {
			return item, true
		}

		// Dynamic settings are resolved here for the same reason the settings page
		// resolves them before display: the query blocker must render the actual
		// input widget, not the placeholder metadata entry.
		for _, callback := range pluginInstance.DynamicSettingCallbacks {
			newSettingDefinition := callback(ctx, key)
			if newSettingDefinition.Value != nil && newSettingDefinition.Type != definition.PluginSettingDefinitionTypeDynamic {
				return newSettingDefinition, true
			}
		}
		return definition.PluginSettingDefinitionItem{}, false
	}

	return definition.PluginSettingDefinitionItem{}, false
}

func (m *Manager) getEffectiveQueryRequirementValidators(requirement MetadataQueryRequirement, item definition.PluginSettingDefinitionItem) []validator.PluginSettingValidator {
	if len(requirement.Validators) > 0 {
		return requirement.Validators
	}

	switch v := item.Value.(type) {
	case *definition.PluginSettingValueTextBox:
		return v.Validators
	case *definition.PluginSettingValueSelect:
		return v.Validators
	case *definition.PluginSettingValueSelectAIModel:
		return v.Validators
	default:
		return nil
	}
}

func (m *Manager) withEffectiveRequirementValidators(item definition.PluginSettingDefinitionItem, validators []validator.PluginSettingValidator) definition.PluginSettingDefinitionItem {
	if len(validators) == 0 {
		return item
	}

	switch v := item.Value.(type) {
	case *definition.PluginSettingValueTextBox:
		copy := *v
		copy.Validators = validators
		item.Value = &copy
	case *definition.PluginSettingValueSelect:
		copy := *v
		copy.Validators = validators
		item.Value = &copy
	case *definition.PluginSettingValueSelectAIModel:
		copy := *v
		copy.Validators = validators
		item.Value = &copy
	}

	return item
}

func (m *Manager) translateQueryRequirementMessage(ctx context.Context, pluginInstance *Instance, message common.I18nString, validationMessage string) string {
	if strings.TrimSpace(string(message)) != "" {
		return m.translatePlugin(ctx, pluginInstance, string(message))
	}
	if strings.TrimSpace(validationMessage) != "" {
		return i18n.GetI18nManager().TranslateWox(ctx, strings.TrimPrefix(validationMessage, "i18n:"))
	}
	return i18n.GetI18nManager().TranslateWox(ctx, "plugin_query_requirement_settings_message")
}

func validateQueryRequirementValue(value string, validators []validator.PluginSettingValidator) string {
	for _, item := range validators {
		switch item.Type {
		case validator.PluginSettingValidatorTypeNotEmpty:
			if strings.TrimSpace(value) == "" {
				return "i18n:ui_validator_value_can_not_be_empty"
			}
		case validator.PluginSettingValidatorTypeIsNumber:
			numberValidator, ok := item.Value.(*validator.PluginSettingValidatorIsNumber)
			if !ok || numberValidator == nil {
				return "i18n:ui_validator_invalid_value"
			}
			if numberValidator.IsInteger {
				if _, err := strconv.Atoi(value); err != nil {
					return "i18n:ui_validator_must_be_integer"
				}
			} else if numberValidator.IsFloat {
				if _, err := strconv.ParseFloat(value, 64); err != nil {
					return "i18n:ui_validator_must_be_number"
				}
			}
		}
	}

	return ""
}
