import 'dart:async';
import 'dart:io';
import 'dart:math' as math;
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:wox/components/wox_image_view.dart';
import 'package:wox/entity/wox_image.dart';
import 'package:wox/enums/wox_image_type_enum.dart';
import 'package:wox/utils/colors.dart';
import 'package:wox/utils/wox_hotkey_display_util.dart';
import 'package:wox/utils/wox_interface_size_util.dart';
import 'package:wox/utils/wox_system_wallpaper_util.dart';
import 'package:wox/utils/wox_theme_util.dart';

part 'wox_demo_popover.dart';
part 'wox_demo_utils.dart';
part 'wox_demo_desktop.dart';
part 'wox_demo_window.dart';
part 'wox_demo_action_panel.dart';
part 'wox_demo_glance_accessory.dart';
part 'wox_demo_hint_card.dart';
part 'wox_tray_query_icon.dart';
part 'wox_theme_swatch_icon.dart';
part 'wox_main_hotkey_demo.dart';
part 'wox_selection_hotkey_demo.dart';
part 'wox_selection_space_quick_look_demo.dart';
part 'wox_query_hotkeys_demo.dart';
part 'wox_query_shortcuts_demo.dart';
part 'wox_tray_queries_demo.dart';
part 'wox_plugin_store_demo.dart';
part 'wox_ai_command_default_action_demo.dart';
part 'wox_theme_install_demo.dart';
part 'wox_theme_store_demo.dart';
part 'wox_glance_demo.dart';
part 'wox_query_concept_demo.dart';
