export interface Theme {
  ThemeId: string
  ThemeName: string
  ThemeAuthor: string
  ThemeUrl: string
  AppBackgroundColor: string
  AppPaddingLeft: number
  AppPaddingTop: number
  AppPaddingRight: number
  AppPaddingBottom: number
  ResultContainerPaddingLeft: number
  ResultContainerPaddingTop: number
  ResultContainerPaddingRight: number
  ResultContainerPaddingBottom: number
  ResultItemBorderRadius: number
  ResultItemPaddingLeft: number
  ResultItemPaddingTop: number
  ResultItemPaddingRight: number
  ResultItemPaddingBottom: number
  ResultItemTitleColor: string
  ResultItemSubTitleColor: string
  ResultItemBorderLeft: string
  ResultItemActiveBackgroundColor: string
  ResultItemActiveTitleColor: string
  ResultItemActiveSubTitleColor: string
  ResultItemActiveBorderLeft: string
  QueryBoxFontColor: string
  QueryBoxBackgroundColor: string
  QueryBoxBorderRadius: number
  ActionContainerBackgroundColor: string
  ActionContainerHeaderFontColor: string
  ActionContainerPaddingLeft: number
  ActionContainerPaddingTop: number
  ActionContainerPaddingRight: number
  ActionContainerPaddingBottom: number
  ActionItemActiveBackgroundColor: string
  ActionItemActiveFontColor: string
  ActionItemFontColor: string
  ActionQueryBoxFontColor: string
  ActionQueryBoxBackgroundColor: string
  ActionQueryBoxBorderRadius: number
  PreviewFontColor: string
  PreviewSplitLineColor: string
  PreviewPropertyTitleColor: string
  PreviewPropertyContentColor: string
}