source_file = [
   'tvgArray.h',
   'tvgCommon.h',
   'tvgColor.h',
   'tvgCompressor.h',
   'tvgInlist.h',
   'tvgLock.h',
   'tvgMap.h',
   'tvgMath.h',
   'tvgStr.h',
   'tvgCompressor.cpp',
   'tvgMath.cpp',
   'tvgStr.cpp'
]

utils_dep = declare_dependency(
    include_directories : include_directories('.'),
    sources : source_file)