package engine

var zoneAliases = map[string]string{
	// UTC
	"utc": "UTC",
	"gmt": "UTC",

	// Asia
	"shanghai":             "Asia/Shanghai",
	"beijing":              "Asia/Shanghai",
	"china":                "Asia/Shanghai",
	"cn":                   "Asia/Shanghai",
	"shenzhen":             "Asia/Shanghai",
	"guangzhou":            "Asia/Shanghai",
	"chengdu":              "Asia/Shanghai",
	"sz":                   "Asia/Shanghai",
	"bj":                   "Asia/Shanghai",
	"sh":                   "Asia/Shanghai",
	"gz":                   "Asia/Shanghai",
	"cd":                   "Asia/Shanghai",
	"hongkong":             "Asia/Hong_Kong",
	"hong kong":            "Asia/Hong_Kong",
	"hk":                   "Asia/Hong_Kong",
	"tokyo":                "Asia/Tokyo",
	"japan":                "Asia/Tokyo",
	"jp":                   "Asia/Tokyo",
	"jst":                  "Asia/Tokyo",
	"osaka":                "Asia/Tokyo",
	"singapore":            "Asia/Singapore",
	"sg":                   "Asia/Singapore",
	"taipei":               "Asia/Taipei",
	"taiwan":               "Asia/Taipei",
	"tw":                   "Asia/Taipei",
	"seoul":                "Asia/Seoul",
	"korea":                "Asia/Seoul",
	"south korea":          "Asia/Seoul",
	"kr":                   "Asia/Seoul",
	"kst":                  "Asia/Seoul",
	"bangkok":              "Asia/Bangkok",
	"thailand":             "Asia/Bangkok",
	"th":                   "Asia/Bangkok",
	"dubai":                "Asia/Dubai",
	"uae":                  "Asia/Dubai",
	"united arab emirates": "Asia/Dubai",
	"ae":                   "Asia/Dubai",
	"delhi":                "Asia/Kolkata",
	"mumbai":               "Asia/Kolkata",
	"india":                "Asia/Kolkata",
	"in":                   "Asia/Kolkata",
	"jakarta":              "Asia/Jakarta",
	"indonesia":            "Asia/Jakarta",
	"id":                   "Asia/Jakarta",
	"malaysia":             "Asia/Kuala_Lumpur",
	"my":                   "Asia/Kuala_Lumpur",
	"philippines":          "Asia/Manila",
	"ph":                   "Asia/Manila",
	"vietnam":              "Asia/Ho_Chi_Minh",
	"vn":                   "Asia/Ho_Chi_Minh",
	"saudi arabia":         "Asia/Riyadh",
	"sa":                   "Asia/Riyadh",
	"israel":               "Asia/Jerusalem",
	"il":                   "Asia/Jerusalem",

	// Europe
	"lisbon":         "Europe/Lisbon",
	"portugal":       "Europe/Lisbon",
	"london":         "Europe/London",
	"inverness":      "Europe/London",
	"scotland":       "Europe/London",
	"uk":             "Europe/London",
	"gb":             "Europe/London",
	"united kingdom": "Europe/London",
	"great britain":  "Europe/London",
	"copenhagen":     "Europe/Copenhagen",
	"denmark":        "Europe/Copenhagen",
	"paris":          "Europe/Paris",
	"france":         "Europe/Paris",
	"fr":             "Europe/Paris",
	"cet":            "Europe/Paris",
	"cest":           "Europe/Paris",
	"berlin":         "Europe/Berlin",
	"germany":        "Europe/Berlin",
	"de":             "Europe/Berlin",
	"rome":           "Europe/Rome",
	"italy":          "Europe/Rome",
	"it":             "Europe/Rome",
	"madrid":         "Europe/Madrid",
	"spain":          "Europe/Madrid",
	"es":             "Europe/Madrid",
	"amsterdam":      "Europe/Amsterdam",
	"netherlands":    "Europe/Amsterdam",
	"nl":             "Europe/Amsterdam",
	"brussels":       "Europe/Brussels",
	"belgium":        "Europe/Brussels",
	"be":             "Europe/Brussels",
	"zurich":         "Europe/Zurich",
	"switzerland":    "Europe/Zurich",
	"ch":             "Europe/Zurich",
	"moscow":         "Europe/Moscow",
	"russia":         "Europe/Moscow",
	"ru":             "Europe/Moscow",
	"stockholm":      "Europe/Stockholm",
	"sweden":         "Europe/Stockholm",
	"se":             "Europe/Stockholm",
	"vienna":         "Europe/Vienna",
	"austria":        "Europe/Vienna",
	"at":             "Europe/Vienna",
	"warsaw":         "Europe/Warsaw",
	"poland":         "Europe/Warsaw",
	"pl":             "Europe/Warsaw",
	"turkey":         "Europe/Istanbul",
	"tr":             "Europe/Istanbul",
	"istanbul":       "Europe/Istanbul",
	"kemer":          "Europe/Istanbul",

	// North America
	"new york":                 "America/New_York",
	"nyc":                      "America/New_York",
	"ny":                       "America/New_York",
	"us":                       "America/New_York",
	"usa":                      "America/New_York",
	"america":                  "America/New_York",
	"united states":            "America/New_York",
	"united states of america": "America/New_York",
	"et":                       "America/New_York",
	"est":                      "America/New_York",
	"edt":                      "America/New_York",
	"eastern":                  "America/New_York",
	"eastern time":             "America/New_York",
	"la":                       "America/Los_Angeles",
	"los angeles":              "America/Los_Angeles",
	"sf":                       "America/Los_Angeles",
	"pt":                       "America/Los_Angeles",
	"pst":                      "America/Los_Angeles",
	"pdt":                      "America/Los_Angeles",
	"pacific":                  "America/Los_Angeles",
	"pacific time":             "America/Los_Angeles",
	"honolulu":                 "Pacific/Honolulu",
	"hawaii":                   "Pacific/Honolulu",
	"chicago":                  "America/Chicago",
	"chi":                      "America/Chicago",
	"ct":                       "America/Chicago",
	"cst":                      "America/Chicago",
	"cdt":                      "America/Chicago",
	"central":                  "America/Chicago",
	"central time":             "America/Chicago",
	"denver":                   "America/Denver",
	"mt":                       "America/Denver",
	"mst":                      "America/Denver",
	"mdt":                      "America/Denver",
	"mountain":                 "America/Denver",
	"mountain time":            "America/Denver",
	"toronto":                  "America/Toronto",
	"canada":                   "America/Toronto",
	"ca":                       "America/Toronto",
	"vancouver":                "America/Vancouver",
	"seattle":                  "America/Los_Angeles",
	"mill valley":              "America/Los_Angeles",
	"marin county":             "America/Los_Angeles",
	"boston":                   "America/New_York",
	"washington":               "America/New_York",
	"dc":                       "America/New_York",
	"miami":                    "America/New_York",
	"dallas":                   "America/Chicago",
	"houston":                  "America/Chicago",
	"mexico":                   "America/Mexico_City",
	"mx":                       "America/Mexico_City",
	"mexico city":              "America/Mexico_City",

	// Australia & New Zealand
	"sydney":      "Australia/Sydney",
	"wollongong":  "Australia/Sydney",
	"nsw":         "Australia/Sydney",
	"australia":   "Australia/Sydney",
	"au":          "Australia/Sydney",
	"aest":        "Australia/Sydney",
	"aedt":        "Australia/Sydney",
	"melbourne":   "Australia/Melbourne",
	"brisbane":    "Australia/Brisbane",
	"perth":       "Australia/Perth",
	"auckland":    "Pacific/Auckland",
	"new zealand": "Pacific/Auckland",
	"nz":          "Pacific/Auckland",
	"wellington":  "Pacific/Auckland",

	// South America
	"sao paulo":    "America/Sao_Paulo",
	"brazil":       "America/Sao_Paulo",
	"br":           "America/Sao_Paulo",
	"buenos aires": "America/Argentina/Buenos_Aires",
	"argentina":    "America/Argentina/Buenos_Aires",
	"ar":           "America/Argentina/Buenos_Aires",
	"rio":          "America/Sao_Paulo",
	"santiago":     "America/Santiago",
	"chile":        "America/Santiago",
	"cl":           "America/Santiago",
	"lima":         "America/Lima",
	"peru":         "America/Lima",
	"pe":           "America/Lima",

	// Africa
	"cairo":        "Africa/Cairo",
	"egypt":        "Africa/Cairo",
	"eg":           "Africa/Cairo",
	"johannesburg": "Africa/Johannesburg",
	"south africa": "Africa/Johannesburg",
	"za":           "Africa/Johannesburg",
	"lagos":        "Africa/Lagos",
	"nigeria":      "Africa/Lagos",
	"ng":           "Africa/Lagos",
	"nairobi":      "Africa/Nairobi",
	"kenya":        "Africa/Nairobi",
	"ke":           "Africa/Nairobi",
	"casablanca":   "Africa/Casablanca",
	"morocco":      "Africa/Casablanca",
	"ma":           "Africa/Casablanca",
}

// ZoneAliases returns independent static lookup data for a catalog.
func ZoneAliases() map[string]string {
	result := map[string]string{}
	for k, v := range zoneAliases {
		result[k] = v
	}
	for k, v := range map[string]string{"ist": "Asia/Kolkata", "ldn": "Europe/London", "são paulo": "America/Sao_Paulo", "jfk": "America/New_York", "lhr": "Europe/London", "sfo": "America/Los_Angeles", "lax": "America/Los_Angeles", "san francisco": "America/Los_Angeles"} {
		result[k] = v
	}
	return result
}
